### ISSUE TITLE
好作品，但是怎么添加自己本地的音乐

### ISSUE THREAD

**Issue by JoyBoy521** [OrageKK/vuepress-plugin-meting2#1]
怎么添加自己本地的音乐，就是我把音乐文件放到了public里，但是没有添加上去

**Comment by JoyBoy521** [comment]
![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/65ffa8fa-5e48-4732-b43a-0240e6c58c3d)

**Comment by JoyBoy521** [comment]
你看我添加上去了，但是
![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/9bc16637-050f-4126-bf8b-a88a69b3b8c8)
我找遍所有音乐都没有找到我添加的本地音乐

**Comment by OrageKK** [comment]
好好看一下文档哈
-  `<Meting/>` 组件支持 `meting` Options 和 `aplayer` Options，其中 `aplayer` 的 `audio` 选项将自动通过 metingApi 获取，如果想要额外添加 `audio` 的话，可以通过 `additionalAudios` 选项实现

![CleanShot 2024-06-06 at 14 44 48@2x](https://github.com/OrageKK/vuepress-plugin-meting2/assets/18461481/aa56f73e-7183-4061-bb52-cee72d65cf48)

**Comment by JoyBoy521** [comment]
![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/1370de30-14ac-487e-9ec0-0935942716aa)
我也添加了。但是没有用

**Comment by JoyBoy521** [comment]
是不是我配置写错了

**Comment by OrageKK** [comment]
> ![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/1370de30-14ac-487e-9ec0-0935942716aa)
> 
> 我也添加了。但是没有用

你类型都报错了。好好看文档行嘛，我没有义务教你怎么写ts

**Comment by OrageKK** [comment]
> 是不是我配置写错了

首先`additionalAudios`是数组，数组里是Audio类型
你的`additionalAudios`是对象，对象是个数组？

**Comment by JoyBoy521** [comment]
![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/155fb578-9019-4082-a934-f64dfc09e7c8)
我寻思着我照着你的写的additionalAudios，我也没写错啊

**Comment by JoyBoy521** [comment]
![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/014b3f35-f558-401a-a162-9b3f67e99ffe)
照着你的写也报错，哥

**Comment by JoyBoy521** [comment]
> > 是不是我配置写错了
> 
> 首先`additionalAudios`是数组，数组里是Audio类型 你的`additionalAudios`是对象，对象是个数组？

好我去试试

**Comment by OrageKK** [comment]
> ![image](https://private-user-images.githubusercontent.com/154486203/337177849-014b3f35-f558-401a-a162-9b3f67e99ffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjE4MTYsIm5iZiI6MTcxNzY2MTUxNiwicGF0aCI6Ii8xNTQ0ODYyMDMvMzM3MTc3ODQ5LTAxNGIzZjM1LWY1NTgtNDAxYS1hMTYyLTliM2Y2N2U5OWZmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwODExNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2QxZTJmNzYzMjA0MWQwYjNhNWY3MDYyYzBiNzRiNzIzYjA3MmE5MDU3ZDc1MDQwMTc0ODkxNTk5ZmIyZTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-gF9-mPGHBLjOaFOEEXdRIX6Ivxo7VrtdR6NSoD45JU) 照着你的写也报错，哥

我建议你先去学习一下ts或者js怎么写，你那是照着我的写的吗o(╥﹏╥)o

**Comment by JoyBoy521** [comment]
![image](https://github.com/OrageKK/vuepress-plugin-meting2/assets/154486203/d16d4854-7ffe-4b95-997f-ec9196aa53fd)
是这样写吗哥

**Comment by JoyBoy521** [comment]
谢谢你哥，弄好了，我爱你哥

**Comment by JoyBoy521** [comment]
真的很感谢，大哥打扰你了，终于弄好了，哈哈哈，大哥我真的爱你

**Comment by JoyBoy521** [comment]
谢谢哥

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月6日(周四) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OrageKK/vuepress-plugin-meting2] 好作品，但是怎么添加自己本地的音乐 (Issue #1)




  
 照着你的写也报错，哥
  
我建议你先去学习一下ts或者js怎么写，你那是照着我的写的吗o(╥﹏╥)o

**Comment by OrageKK** [comment]
> 谢谢你哥，弄好了，我爱你哥

弄好了就行，你这语法基础太薄弱了
